//----------------------------------------------------------------------
/**
 * @file vf_mba_defines.inc
 * @brief Defines VF MBA defines.
 */
/*
 * Copyright (C) 2009-2016 Verifore, Inc.
 * All rights reserved. Property of Verifore, Inc.
 * Restricted rights to use, duplicate or disclose
 * this code are granted through contract.
 */
//----------------------------------------------------------------------
`ifndef _VF_MBA_DEFINES_INC_
`define _VF_MBA_DEFINES_INC_
//`protect

`define VF_MBA_ADR_WIDTH      30
`define VF_MBA_BST_WIDTH      10
`define VF_MBA_DT_WIDTH       128
`define VF_MBA_BEN_WIDTH      (`VF_MBA_DT_WIDTH/8)

//`endprotect
`endif // `ifndef _VF_MBA_DEFINES_INC_
